# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'grpc-agw action'
description: 'GitHub Action for GoReleaser, a release automation tool for Go projects'
author: 'huangjian'
branding:
  color: 'green'
  icon: 'package'

inputs:
  distribution:
    description: 'GoReleaser Distribution (goreleaser or goreleaser-pro)'
    default: 'goreleaser'
    required: false
  version:
    description: 'GoReleaser version'
    default: 'latest'
    required: false
  args:
    description: 'Arguments to pass to GoReleaser'
    required: false
  workdir:
    description: 'Working directory (below repository root)'
    default: '.'
    required: false
  install-only:
    description: 'Just install GoReleaser'
    default: 'false'
    required: false

outputs:
  artifacts:
    description: 'Build result artifacts'
  metadata:
    description: 'Build result metadata'
